"""Добавлен столбец metro_coords в таблицу Users

Revision ID: 2dd041b09b91
Revises: e5b3d4e4a815
Create Date: 2025-06-12 19:07:06.338112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd041b09b91'
down_revision: Union[str, None] = 'e5b3d4e4a815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metro_coords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metro_coords')
    # ### end Alembic commands ###
