"""Add Mutes and Quote

Revision ID: 639c1db58f9c
Revises: 2f2853c3bafc
Create Date: 2025-06-09 15:43:44.513726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639c1db58f9c'
down_revision: Union[str, None] = '2f2853c3bafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('mute_start', sa.String(), nullable=False),
    sa.Column('mute_end', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_username', sa.String(), nullable=True),
    sa.Column('author_first_name', sa.String(), nullable=False),
    sa.Column('quote_text', sa.String(), nullable=False),
    sa.Column('added_by_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.String(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('mutes')
    # ### end Alembic commands ###
