"""Add Ent and Events models

Revision ID: 644c81e411a9
Revises: a68f46f49c3e
Create Date: 2025-06-09 11:29:16.980379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644c81e411a9'
down_revision: Union[str, None] = 'a68f46f49c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entertainments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ent', sa.String(), nullable=False),
    sa.Column('declension', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entertam', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.Column('whom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entertam'], ['entertainments.id'], ),
    sa.ForeignKeyConstraint(['who'], ['users.id'], ),
    sa.ForeignKeyConstraint(['whom'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('entertainments')
    # ### end Alembic commands ###
